services:
  neo4j:
    image: neo4j:latest
    container_name: graph_db
    environment:
        - NEO4J_AUTH=neo4j/ou812sosueme
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    